### PR TITLE
Fix settings.docker.demo.php for Docker Compose v2, memcached

### PR DESCRIPTION
**Pull request by kducharm**
Fixes settings.docker.demo.php for Docker Compose v2, memcached server settings

## QA

- [x] Verify upgrading a site to this branch works
- [x] Memcached should be functioning when used with Docker (host: memcached:11211)

### CODE REVIEW

**Comment by janette** [comment]
@kducharm 
```
                Name                              Command               State                                   Ports                                  
------------------------------------------------------------------------------------------------------------------------------------------------------
ngworldbankcaribbjamdata_browser_1     /opt/bin/entry_point.sh          Up      4444/tcp, 0.0.0.0:32939->5900/tcp                                      
ngworldbankcaribbjamdata_cli_1         /opt/startup.sh /bin/sh -c ...   Up      0.0.0.0:32940->8888/tcp                                                
ngworldbankcaribbjamdata_db_1          /entrypoint.sh mysqld            Up      0.0.0.0:32941->3306/tcp                                                
ngworldbankcaribbjamdata_memcached_1   docker-entrypoint.sh memcached   Up      11211/tcp                                                              
ngworldbankcaribbjamdata_solr_1        /bin/sh -c /opt/startup.sh;      Up      0.0.0.0:32935->8983/tcp                                                
ngworldbankcaribbjamdata_web_1         /bin/sh -c /opt/startup.sh ...   Up      0.0.0.0:32937->443/tcp, 0.0.0.0:32938->80/tcp, 0.0.0.0:32936->8888/tcp 
```
but when I run `ahoy site up` I get
```
ENVIRONMENT set to , but not mapped in settings.php
Drush command terminated abnormally due to an unrecoverable error.
```

**Comment by kducharm** [comment]
@janette can you check that https://github.com/GetDKAN/dkan/commit/b926e2b7359a2dbbf767e10f25a77c950d59d486 is in your branch? That is merged, but I think it's only in 7.x-1.x and not 1.14 atm. It may be in 1.15 but I haven't checked.

**Comment by janette** [comment]
@kducharm that is not in the branch I am updating, also it does not have `.ahoy/docker-compose.common.yml` so I can't apply the patch

**Comment by kducharm** [comment]
@janette Can you try this updated branch, I left in fallbacks for docker-machine so it won't depend on that other DKAN commit

**Comment by kducharm** [comment]
@janette You shouldn't have to add anything to make memcache work if this PR is working (locally)... those lines are in settings.docker.demo.php. I'm not sure how you were testing, but make sure that settings.docker.demo.php got copied to settings.docker.php. If you're using docker machine, `ahoy docker exec env` should output MEMCACHED_PORT_11211_TCP_ADDR, and if so, then settings.docker.php should work.

**Comment by janette** [comment]
@kducharm the output of `ahoy docker exec env` and `settings.docker.php` look good  but if I enable memcache I get this error
```
There are problems with your Memcache configuration. Please review README.txt and visit the Drupal admin status report page for more information.
```
```
Failed to load required file sites/all/modules/contrib/memcache/dmemcache.inc.
```
is that outside the scope of this ticket?

**Pull request merged**
